# Generated by Django 4.0.6 on 2022-11-07 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, default='2022-11-08', verbose_name='期限')),
                ('priority', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
