# Generated by Django 4.0.6 on 2022-12-03 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListTodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=255, null=True, unique=True)),
                ('list_counter', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'list_todo',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, default=datetime.datetime(2022, 12, 5, 5, 25, 13, 578826), verbose_name='期限')),
                ('priority', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TodoApp.listtodo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
