# Generated by Django 4.0.6 on 2022-08-28 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('category', models.CharField(max_length=50)),
                ('deadline', models.DateTimeField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
