# Generated by Django 4.0.6 on 2022-08-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='期限'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateField(),
        ),
    ]
