# Generated by Django 4.0.6 on 2022-09-01 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_todo_status_alter_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='作成日時'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='更新日時'),
        ),
    ]
